config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/', to: 'home#index', as: :home
  get '/accessibility-statement', to: 'home#accessibility_statement'
  get '/cookie-settings', to: 'home#cookie_settings'
  get '/cookie-settings/update', to: 'home#update_cookie_settings'
  get '/cookie-policy', to: 'home#cookie_policy'
  get '/health_check', to: 'health_check#index'

  # API endpoints here
  namespace :api do
    namespace :v1 do
      get '/oauth2/authorize', to: 'openid_connect#authorize'
      post '/oauth2/token', to: 'openid_connect#token'
      get '/oauth2/userInfo', to: 'openid_connect#user_info'
      get '/organisation-search', to: 'organisation#search'
    end
    namespace :v2 do
      get '/oauth2/authorize', to: 'auth_authorize#authorize'
    end
  end

  namespace 'base', path: 'auth' do
    get '/sign-up', to: 'registrations#new', as: :new_user_registration
    post '/sign-up', to: 'registrations#create', as: :user_registration
    get '/domain-not-on-allow-list', to: 'registrations#domain_not_on_allow_list', as: :domain_not_on_allow_list
    get '/users/confirm', to: 'users#confirm_new', as: :users_confirm_path
    post '/users/confirm', to: 'users#confirm'
    get '/resend_confirmation_email', to: 'users#resend_confirmation_email', as: :resend_confirmation_email
    get '/sign-in', to: 'sessions#new', as: :new_user_session
    post '/sign-in', to: 'sessions#create', as: :user_session
    get '/users/forgot-password', to: 'passwords#new', as: :new_user_password
    post '/users/password', to: 'passwords#create'
    get '/users/forgot-password-confirmation', to: 'passwords#confirm_new', as: :confirm_new_user_password
    get '/users/password', to: 'passwords#edit', as: :edit_user_password
    put '/users/password', to: 'passwords#update'
    get '/users/password-reset-success', to: 'passwords#password_reset_success', as: :password_reset_success
  end

  get '/404', to: 'errors#not_found'
  get '/406', to: 'errors#not_acceptable'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'
  get '/service-unavailable', to: 'errors#service_unavailable'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def accessibility_statement; end

  def cookie_settings; end

  def cookie_policy; end

  def update_cookie_settings
    update_cookie_preferences

    cookies[TailspendIdam.cookie_settings_name] = {
      value: helpers.cookie_preferences_settings.to_json,
      expires: 1.year.from_now
    }

    params[:cookies_updated] = true

    respond_to do |format|
      format.html { render 'home/cookie_settings' }
      format.json { render json: { cookies_updated: true } }
    end
  end

  private

  def update_cookie_preferences
    cookie_prefixes = []

    COOKIE_UPDATE_OPTIONS.each do |cookie_update_option|
      if params[cookie_update_option[:param_name]] == 'true'
        helpers.cookie_preferences_settings[cookie_update_option[:cookie_name]] = true
      else
        helpers.cookie_preferences_settings[cookie_update_option[:cookie_name]] = false

        cookie_prefixes += cookie_update_option[:cookie_prefixes]
      end
    end

    delete_unwanted_cookie(cookie_prefixes)

    helpers.cookie_preferences_settings['settings_viewed'] = true
  end

  def delete_unwanted_cookie(cookie_prefixes)
    return unless cookie_prefixes.any?

    cookies.each do |cookie_name, _|
      if cookie_prefixes.any? { |cookie_prefix| cookie_name.start_with? cookie_prefix }
        cookies.delete(cookie_name, path: '/', domain: '.crowncommercial.gov.uk')
        cookies.delete(cookie_name, path: '/', domain: '.gca.gov.uk')
      end
    end
  end

  COOKIE_UPDATE_OPTIONS = [
    {
      param_name: :ga_cookie_usage,
      cookie_name: 'usage',
      cookie_prefixes: %w[_ga _gi]
    },
    {
      param_name: :glassbox_cookie_usage,
      cookie_name: 'glassbox',
      cookie_prefixes: %w[_cls]
    }
  ].freeze
end

app/views/home/_ga_cookies_info.html.erb
<div class="govuk-body">
  <p>
    <%= t('.we_use_ga') %>
  </p>

  <p>
    <%= t('.ga_list.title') %>
  </p>
  
  <ul class="govuk-list govuk-list--bullet">
    <li><%= t('.ga_list.item_1') %></li>
    <li><%= t('.ga_list.item_2') %></li>
    <li><%= t('.ga_list.item_3') %></li>
    <li><%= t('.ga_list.item_4') %></li>
  </ul>

  <p>
    <%= t('.we_dont_collect') %>
  </p>

  <p>
    <%= t('.we_dont_allow') %>
  </p>
</div>

app/views/home/_glassbox_cookies_info.html.erb
<div class="govuk-body">
  <p>
    <%= t('.we_use_glassbox') %>
  </p>

  <p>
    <%= t('.glassbox_list.title') %>
  </p>
  
  <ul class="govuk-list govuk-list--bullet">
    <li><%= t('.glassbox_list.item_1') %></li>
    <li><%= t('.glassbox_list.item_2') %></li>
    <li><%= t('.glassbox_list.item_3') %></li>
    <li><%= t('.glassbox_list.item_4') %></li>
  </ul>

  <p>
    <%= t('.we_dont_collect') %>
  </p>

  <p>
    <%= t('.we_dont_allow') %>
  </p>
</div>

app/views/home/accessibility_statement.html.erb
<%= content_for :page_title, t('.heading') %>

<div class= 'govuk-!-width-three-quarters govuk-body'>
  <h1 class='govuk-heading-l'>
    <%= t('.heading') %>
  </h1>

  <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">

  <div>
    <p>
      <%= t('.this_statement') %> <br>
      <%= link_to t('.tailspend_link'), t('.tailspend_link'), class: 'govuk-link govuk-link--no-visited-state' %>
    </p>
    <p>
      <%= t('.this_website') %>
    </p>
    <ul>
      <li> <%= t('.list_1_change_colours') %> </li>
      <li> <%= t('.list_1_navigate_keyboard') %> </li>
      <li> <%= t('.list_1_navigate_speach') %> </li>
      <li> <%= t('.list_1_navigate_listen') %> </li>
    </ul>
    <p>
      <%= t('.website_text_simple') %>
    </p>
    <p>
      <%= t('.ability_net_text_html', ability_link: link_to(t('.ability_net'), t('.ability_net_link'), class: 'govuk-link govuk-link--no-visited-state')) %>
    </p>
  </div>

  <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_how_accessible') %>
    </h2>
    <p>
      <%= t('.we_know') %>
    </p>
    <ul>
      <li> <%= t('.list_2_email') %> </li>
      <li> <%= t('.list_2_decorative') %> </li>
    </ul>
  </div>

  <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_what_to_do') %>
    </h2>
    <p>
      <%= t('.if_you_need') %>
    </p>
    <ul>
      <li> <%= t('.email') %> <%= mail_to t('.email_link'), t('.email_link'), class: 'govuk-link govuk-link--no-visited-state' %> </li>
      <li> <%= t('.call') %> </li>
    </ul>
    <p>
      <%= t('.well_consider') %>
    </p>
  </div>

  <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_reporting') %>
    </h2>
    <p>
      <%= t('.we_are_always_looking_html', email: mail_to(t('.email_link'),  t('.email_link'), class: 'govuk-link govuk-link--no-visited-state')) %>
    </p>
  </div>

  <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_enforcement') %>
    </h2>
    <p>
      <%= t('.equality') %>
      <%= link_to t('.equality_link_text'), t('.equality_link'), class: 'govuk-link govuk-link--no-visited-state' %>.
    </p>
  </div>

  <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_technical_information') %>
    </h2>
    <p>
      <%= t('.CCS_is_committed') %>
    </p>
    <p>
      <%= t('.this_website_partially_1') %>
      <%= link_to t('.accessibility_guidelines_link_text'), t('.accessibility_guidelines_link'), class: 'govuk-link govuk-link--no-visited-state' %>,
      <%= t('.this_website_partially_2') %>
    </p>
  </div>

  <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_non_accessible') %>
    </h2>
    <p>
      <%= t('.the_content') %>
    </p>
  </div>

  <hr class="govuk-section-break govuk-section-break--m">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_non_compliance') %>
    </h2>
    <div>
      <h3 class='govuk-heading-s'>
        <%= t('.autocomplete_heading') %>
      </h3>
      <p>
        <%= t('.autocomplete_issue') %>
      </p>
    </div>
  </div>

  <hr class="govuk-section-break govuk-section-break--l">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_content_not_in_scope') %> 
    </h2>
    <div>
      <h3 class='govuk-heading-s'>
        <%= t('.core_tailspend') %>
      </h3>
      <p>
        <%= t('.several_aspects') %>
      </p>
    </div>
  </div>

  <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

  <div>
    <h2 class='govuk-heading-m'>
      <%= t('.heading_preparation') %> 
    </h2>
    <p>
      <%= t('.this_statement_date') %>
    </p>

    <hr class="govuk-section-break govuk-section-break--m">

    <div>
      <h3 class='govuk-heading-s'>
        <%= t('.heading_how_we_tested') %> 
      </h3>
      <p>
        <%= t('.website_last_tested') %>
      </p>
      <p>
        <%= t('.the_complete_journey') %>
      </p>
    </div>
  </div>
  <hr class="govuk-section-break govuk-section-break--visible">
</div>

app/views/home/cookie_policy.html.erb
<%= content_for :page_title, t('.heading') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-three-quarters">
    <h1 class="govuk-heading-xl">
      <%= t('.heading') %>
    </h1>
    <p class="govuk-body">
      <%= t('.what_are_cookies') %>
    </p>
  </div>
</div>

<hr class="govuk-section-break govuk-section-break--m">

<div class="govuk-grid-row">
  <div class="govuk-grid-column-three-quarters">
    <h2 class="govuk-heading-m">
      <%= t('home.cookies.measure_website_use.title') %>
    </h2>

    <div>
      <h3 class="govuk-heading-s">
        <%= t('home.cookies.measure_website_use.ga') %>
      </h3>

      <%= render partial: 'home/ga_cookies_info' %>

      <p class="govuk-body">
        <%= t('.ga_sets_following_cookies') %>
      </p>

      <%= govuk_table(
        [
          {
            text: t('home.cookies.name')
          },
          {
            text: t('home.cookies.purpose')
          },
          {
            text: t('home.cookies.expires')
          }
        ],
        (1..3).map do |i|
          [
            {
              text: t(".ga_cookies.row_#{i}.name")
            },
            {
              text: t(".ga_cookies.row_#{i}.purpose")
            },
            {
              text: t(".ga_cookies.row_#{i}.expires")
            }
          ]
        end
      ) %>
    </div>

    <hr class="govuk-section-break govuk-section-break--m">

    <div>
      <h3 class="govuk-heading-s">
        <%= t('home.cookies.measure_website_use.glassbox') %>
      </h3>

      <%= render partial: 'home/glassbox_cookies_info' %>

      <p class="govuk-body">
        <%= t('.glassbox_sets_following_cookies') %>
      </p>

      <%= govuk_table(
        [
          {
            text: t('home.cookies.name')
          },
          {
            text: t('home.cookies.purpose')
          },
          {
            text: t('home.cookies.expires')
          }
        ],
        (1..2).map do |i|
          [
            {
              text: t(".glassbox_cookies.row_#{i}.name")
            },
            {
              text: t(".glassbox_cookies.row_#{i}.purpose")
            },
            {
              text: t(".glassbox_cookies.row_#{i}.expires")
            }
          ]
        end
      ) %>
    </div>
  </div>
</div>

<hr class="govuk-section-break govuk-section-break--m">

<div class="govuk-grid-row">
  <div class="govuk-grid-column-three-quarters">
    <h2 class="govuk-heading-m">
      <%= t('home.cookies.strictly_necessary_cookies') %>
    </h2>

    <h3 class="govuk-heading-s">
      <%= t('.cookies_banner') %>
    </h3>

    <p class="govuk-body">
      <%= t('.you_may_see_a_banner') %>
    </p>

    <%= govuk_table(
      [
        {
          text: t('home.cookies.name')
        },
        {
          text: t('home.cookies.purpose')
        },
        {
          text: t('home.cookies.expires')
        }
      ],
      [
        [
          {
            text: TailspendIdam.cookie_settings_name
          },
          {
            text: t(".cookie_banner_cookies.row_1.purpose")
          },
          {
            text: t(".cookie_banner_cookies.row_1.expires")
          }
        ],
        [
          {
            text: t(".cookie_banner_cookies.row_2.name")
          },
          {
            text: t(".cookie_banner_cookies.row_2.purpose")
          },
          {
            text: t(".cookie_banner_cookies.row_2.expires")
          }
        ]
      ]
    ) %>
  </div>
</div>

<hr class="govuk-section-break govuk-section-break--m">

<div class="govuk-grid-row">
  <div class="govuk-grid-column-three-quarters">
    <h2 class="govuk-heading-m">
      <%= t('.change_your_settings') %>
    </h2>

    <p class="govuk-body">
      <%= t('.change_settings_html', change_settings_link: link_to(t('.change_settings_link_text'), cookie_settings_path, class: 'govuk-link govuk-link--no-visited-state') ) %>
    </p>

    <p class="govuk-body">
      <%= t('.last_updated') %>
    </p>
  </div>
</div>

app/views/home/cookie_settings.html.erb
<%= content_for :page_title, t('.heading') %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-three-quarters" id="cookie-settings-saved" <%= 'hidden' unless params[:cookies_updated] %>>
    <%= govuk_notification_banner(t('.cookies_saved'), true) %>
  </div>
  <div class="govuk-grid-column-three-quarters" id="cookie-settings-not-saved" hidden>
    <%= govuk_notification_banner(t('.cookies_not_saved'), classes: 'govuk-notification-banner--error', title_text: t('.error')) %>
  </div>
</div>

<div class="govuk-grid-row govuk-body">
  <div class="govuk-grid-column-three-quarters">
    <h1 class="govuk-heading-xl">
      <%= t('.heading') %>
    </h1>
    <p>
      <%= t('.what_are_cookies') %>
    </p>
    <p >
      <%= t('.why_we_use_them') %>
    </p>
  </div>
</div>

<div class="govuk-grid-row govuk-body">
  <div class="govuk-grid-column-three-quarters">
    <h2 class="govuk-heading-m">
      <%= t('.cookie_settings') %>
    </h2>
    <p>
      <%= t('.the_number_we_use') %>
    </p>
  </div>
</div>

<%= form_with method: :get, url: cookie_settings_update_path, local: true, id: 'update-cookie-setings', html: { specialvalidation: true } do |f| %>
  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-three-quarters">
      <h2 class="govuk-heading-m">
        <%= t('home.cookies.measure_website_use.title') %>
      </h2>

      <%= govuk_radios(
        :ga_cookie_usage,
        [
          {
            value: true,
            label: {
              text: t('.use_cookies.ga')
            },
            checked: cookie_preferences_settings['usage'],
          },
          {
            value: false,
            label: {
              text: t('.dont_use_cookies.ga')
            },
            checked: !cookie_preferences_settings['usage'],
          }
        ],
        fieldset: {
          legend: {
            text: t('home.cookies.measure_website_use.ga'),
            classes: 'govuk-fieldset__legend--m'
          }
        },
        hint: {
          text: render(partial: 'home/ga_cookies_info')
        }
      ) %>

      <hr class="govuk-section-break govuk-section-break--m">

      <%= govuk_radios(
        :glassbox_cookie_usage,
        [
          {
            value: true,
            label: {
              text: t('.use_cookies.glassbox')
            },
            checked: cookie_preferences_settings['glassbox'],
          },
          {
            value: false,
            label: {
              text: t('.dont_use_cookies.glassbox')
            },
            checked: !cookie_preferences_settings['glassbox'],
          }
        ],
        fieldset: {
          legend: {
            text: t('home.cookies.measure_website_use.glassbox'),
            classes: 'govuk-fieldset__legend--m'
          }
        },
        hint: {
          text: render(partial: 'home/glassbox_cookies_info')
        }
      ) %>
    </div>
  </div>

  <hr class="govuk-section-break govuk-section-break--m">

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-three-quarters">
      <h2 class="govuk-heading-m">
        <%= t('home.cookies.strictly_necessary_cookies') %>
      </h2>
      <p>
        <%= t('.essential_cookies') %>
      </p>
      <p>
        <%= t('.always_need_to_be_on') %>
      </p>
      <%= link_to t('.find_out_more'), cookie_policy_path, class: 'govuk-link govuk-link--no-visited-state govuk-!-font-size-19' %>
    </div>
  </div>

  <hr class="govuk-section-break govuk-section-break--m">

  <div class="govuk-grid-row govuk-body">
    <div class="govuk-grid-column-three-quarters">
      <%= govuk_button(t('.save_changes'), attributes: { id: 'save-cookie-settings-button' }) %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<%= content_for :page_title, t('.heading') %>
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">
      <%= t('.heading') %>
    </h1>
  </div>
</div>

<div class="govuk-grid-row govuk-body">
  <div class="govuk-grid-column-two-thirds">
    <p>
      <%= t('.the_tailspend_solution') %>
    </p>
    <p>
      <%= t('.to_use_this_service') %>
    </p>
    <p>
      <%= t('.before_you_sign_in_html', registration_link: link_to(t('.create_an_account'), base_new_user_registration_path, class: 'govuk-link govuk-link--no-visited-state')) %>
    </p>
    <p>
      <%= t('.your_org_will_need') %>
    </p>
    <div class="govuk-button-group">
      <%= govuk_button(t('.sign_in_to_ot'), href: ENV['OFFICE_TEAM_GET_URL']) %>
      <%= govuk_button(t('.sign_in_to_unite'), href: ENV['MERCATEO_GET_URL']) %>
    </div>
  </div>
</div>